version: '3.9'

services:
  db:
    container_name: db
    image: mongo:latest
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 1000:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${adminUser}
      - MONGO_INITDB_ROOT_PASSWORD=${adminPassword}
      - MONGO_INITDB_DATABASE=${devDB}

  api:
    build: 
      context: ./api
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./api:/usr/src/app
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_URI: mongodb://db:27017/${devDB}
      DB_USERNAME: ${admin} #Uses admin user for now. hav  not got others working.
      DB_PASSWORD: ${adminPassword}
      DB: ${devDB}
    depends_on:
      - db
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/usr/src
    environment:
      PORT: 8080
      PROXY_API: http://api:3000/

volumes:
  db: {}