version: '3.9'

services:
  db:
    container_name: db
    image: mongo:latest
    restart: always
    volumes:
      - db:/data/db
    ports:
      - 1000:27017

  api:
    build: ./api #Will use Dockerfile as default
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_URI: mongodb://db:27017/prod
    depends_on:
      - db

volumes:
  db: {}

